#
# This workflow was inspired by the example one from
# https://github.com/bast/gtest-demo/blob/master/.github/workflows/test.yml.
#
name: Data Structure and Algorithms Build and Tests

on:
  push:
  pull_request:

env:
  BUILD_DIR: build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -S. -B${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build ${{ env.BUILD_DIR }} --config Debug

    - name: Test
      env:
        GTEST_OUTPUT: xml:testResults/
      run: |
        mkdir build/arrays/testResults
        mkdir build/matrices/testResults
        mkdir build/strings/testResults
        mkdir build/utils/testResults
        ctest --test-dir ${{ env.BUILD_DIR }} -C Debug -T test --output-on-failure

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          build/**/testResults/*.xml

    # This report exceeds the github report limit so it is being commented out
    # - name: Publish Test Results II
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: CTest Tests
    #     path: build/**/testResults/*.xml
    #     reporter: java-junit
